// <auto-generated />
using System;
using ECommerce.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
    [Migration("20240412161340_init")]
========
    [Migration("20240413093725_init")]
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerce.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartDetail");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9793),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7196),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Çakmak",
                            Name = "Çok Amaçlı",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9804),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7212),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Çakmak",
                            Name = "Mumlar İçin",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9804),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7213),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Aksesuar",
                            Name = "Cüzdan",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9806),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7215),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Aksesuar",
                            Name = "Gözlük",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9806),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7216),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Aksesuar",
                            Name = "Kalem",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "Kırmızı",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9891),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7384),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "• Kaplama: Red Matte\r\n• Eşsiz Zippo \"klik\" sesine sahip orijinal Zippo rüzgar geçirmez çakmak.\r\n• Özel hediyelik kutusunda paketlenmiş olarak gelir.\r\n• Tamamı metalden oluşan iç aksam; neredeyse her yerde çalışan rüzgar geçirmez tasarım",
                            ImagePath = "../../images/cakmak/cakmak-kirmizi.jpg",
                            Name = "Çakmak",
                            Price = 100m,
                            Quantity = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Color = "Mavi",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9892),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7388),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "• Kaplama: Indigo\r\n• Eşsiz Zippo \"klik\" sesine sahip orijinal Zippo rüzgar geçirmez çakmak.\r\n• Özel hediyelik kutusunda paketlenmiş olarak gelir.\r\n• Tamamı metalden oluşan iç aksam; neredeyse her yerde çalışan rüzgar geçirmez tasarım",
                            ImagePath = "../../images/cakmak/cakmak-mavi.jpg",
                            Name = "Çakmak",
                            Price = 150m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Color = "Yeşil",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9894),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7390),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "• Kaplama: Green Matte\r\n• Eşsiz Zippo \"klik\" sesine sahip orijinal Zippo rüzgar geçirmez çakmak.\r\n• Özel hediyelik kutusunda paketlenmiş olarak gelir.\r\n• Tamamı metalden oluşan iç aksam; neredeyse her yerde çalışan rüzgar geçirmez tasarım",
                            ImagePath = "../../images/cakmak/cakmak-yesil.jpg",
                            Name = "Çakmak",
                            Price = 200m,
                            Quantity = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Color = "Siyah",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9895),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7394),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "• Kaplama: Black Matte\r\n• Eşsiz Zippo \"klik\" sesine sahip orijinal Zippo rüzgar geçirmez çakmak.\r\n• Özel hediyelik kutusunda paketlenmiş olarak gelir.\r\n• Tamamı metalden oluşan iç aksam; neredeyse her yerde çalışan rüzgar geçirmez tasarım",
                            ImagePath = "../../images/cakmak/cakmak-siyah.jpg",
                            Name = "Çakmak",
                            Price = 120m,
                            Quantity = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Color = "Beyaz",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9896),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7395),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "• Kaplama: White Matte\r\n• Eşsiz Zippo \"klik\" sesine sahip orijinal Zippo rüzgar geçirmez çakmak.\r\n• Özel hediyelik kutusunda paketlenmiş olarak gelir.\r\n• Tamamı metalden oluşan iç aksam; neredeyse her yerde çalışan rüzgar geçirmez tasarım",
                            ImagePath = "../../images/cakmak/cakmak-beyaz.jpg",
                            Name = "Çakmak",
                            Price = 180m,
                            Quantity = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Color = "Siyah",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9898),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7397),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Romantik bir akşam yemeği için mumlar hazır mı? Güzel bir akşam yemeğinde mumları yakmayı Zippo Mum Çakmağına bırakın. Fırçalanmış krom renkli Mum çakmağı yumuşak bir dokunmayla yanmaya hazır sistemi, ayarlanilir alev çıkışı, patentli çocuk-resistans kilidi ve baştan uca 16,5 cm uzunluğunda. Fırçalanmış krom rengine sahip mum çakmağı 3-yıl garantiye sahiptir. Optimum yanma performansı için Zippo Premium Bütan gazı kullanılması önerilir.Romantik bir akşam yemeği için mumlar hazır mı? Güzel bir akşam yemeğinde mumları yakmayı Zippo Mum Çakmağına bırakın. Fırçalanmış krom renkli Mum çakmağı yumuşak bir dokunmayla yanmaya hazır sistemi, ayarlanilir alev çıkışı, patentli çocuk-resistans kilidi ve baştan uca 16,5 cm uzunluğunda. Fırçalanmış krom rengine sahip mum çakmağı 3-yıl garantiye sahiptir. Optimum yanma performansı için Zippo Premium Bütan gazı kullanılması önerilir.",
                            ImagePath = "../../images/cakmak/mum-icin-cakmak.jpg",
                            Name = "Çakmak",
                            Price = 180m,
                            Quantity = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Color = "Mavi",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9899),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7399),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Zippo'nun yepyeni Denim serisinin bir parçası. Cebinizde tarz yaratın! Orijinal Zippo logosuna ve ihtiyacınız olan her şeye uyacak çeşitli bölmelere sahip bir deri-denim Kredi Kartı Tutucu.\r\n\r\nDeri ve Denim Kot Kumaşından Üretilmiştir\r\nKot ve Ten Rengi\r\nYatay biçimli İki Katlı Kredi Kartı Cüzdanı",
                            ImagePath = "../../images/cuzdan/cuzdan-mavi.jpg",
                            Name = "Cüzdan",
                            Price = 150m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Color = "Siyah",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9900),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7400),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Zippo'nun yepyeni Saffiano serisinin bir parçası. Orijinal Zippo logosuna sahip, Saffiano kabartmalı ve çeşitli bölmelere sahip yüksek kaliteli deriden yapılmış bir deri cüzdan, ihtiyacınız olan her şeye uyacak şekilde.\r\n\r\nSafiano Deriden yapılmıştır\r\nYatay formatlı Fermuarlı Cüzdan\r\nBoyutlar: 9cm x 11cm x 2cm\r\nRFID özelliğine sahip\r\nSiyah",
                            ImagePath = "../../images/cuzdan/cuzdan-siyah1.jpg",
                            Name = "Cüzdan",
                            Price = 120m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Color = "Siyah",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9901),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7402),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Zippo'nun yepyeni Saffiano serisinin bir parçası. Orijinal Zippo logosuna sahip, Saffiano kabartmalı ve çeşitli bölmelere sahip yüksek kaliteli deriden yapılmış bir deri cüzdan, ihtiyacınız olan her şeye uyacak şekilde.\r\n\r\nSafiano Deriden yapılmıştır\r\nYatay biçim Üç bölmeli Cüzdan\r\nBoyutlar: 10,5cm x 9cm x 3,5cm\r\nRFID özelliğine sahip\r\nSiyah",
                            ImagePath = "../../images/cuzdan/cuzdan-siyah2.jpg",
                            Name = "Cüzdan",
                            Price = 100m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Color = "Siyah",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9902),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7404),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Renk: Yeşil.\r\nBoyutlar: 10,5 x 8 x 1 cm.\r\nHakiki Deri\r\n6 Kart, 2 İç göz,1 Kimlik gözü\r\nÇevre dostu bir hediye kutusunda paketlenmiştir. Zippo kalitesine uygun olarak Hindistan'da üretilmiştir.Renk: Yeşil.\r\nBoyutlar: 10,5 x 8 x 1 cm.\r\nHakiki Deri\r\n6 Kart, 2 İç göz,1 Kimlik gözü\r\nÇevre dostu bir hediye kutusunda paketlenmiştir. Zippo kalitesine uygun olarak Hindistan'da üretilmiştir.",
                            ImagePath = "../../images/cuzdan/cuzdan-yesil.jpg",
                            Name = "Cüzdan",
                            Price = 100m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Color = "Kırmızı",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9903),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7405),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "G:55mm Y:44mm K:17mm\r\nPolikarbon alaşım\r\nOptik Sınıf: 1\r\n\r\nMaksimum UV koruması\r\n\r\nMikrofiber kılıf\r\nÜcretsiz yanında: Sert karton koruma kabı ve mikrofiber bezPolikarbon alaşım\r\nOptik Sınıf: 1\r\n\r\nMaksimum UV koruması",
                            ImagePath = "../../images/gozluk/gozluk-kirmizi.jpg",
                            Name = "Gözlük",
                            Price = 150m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Color = "Mavi",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9904),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7406),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "G:58mm Y:50mm K:17mm\r\nMetal alaşım\r\nOptik Sınıf: 1\r\nMaksimum UV koruması\r\n\r\nMikrofiber kılıf\r\nÜcretsiz yanında: Sert karton koruma kabı ve mikrofiber bezMetal alaşım\r\nOptik Sınıf: 1\r\nMaksimum UV koruması",
                            ImagePath = "../../images/gozluk/gozluk-mavi.jpg",
                            Name = "Gözlük",
                            Price = 150m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Color = "Siyah",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9905),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7411),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "G:58mm Y:50mm K:17mm\r\nÖn Genişlik: 138mm\r\nSap Uzunluğu: 140mm\r\nMetal alaşım\r\nOptik Sınıf: 1\r\nMaksimum UV korumasıMetal alaşım\r\nOptik Sınıf: 1\r\nMaksimum UV koruması",
                            ImagePath = "../../images/gozluk/gozluk-siyah.jpg",
                            Name = "Gözlük",
                            Price = 150m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Color = "Siyah",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9907),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7413),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Zippo'nun parlak siyah tükenmez kalemi (Ballpoint) çift yönlü açılabilme, Zippo logolu metal klipsli ve orta kalınlıkta siyah uç. Zippo'nun bu kalemi hediye edilmeye uygun özel doğa dostu karton kutusunda iki yıl garanti kapsamındadır.\r\n•Çift Yönlü Açılma\r\n•Tükenmez Kalem (Ball Point)\r\n•Özel doğa dostu karton kutusunda\r\n•Garanti",
                            ImagePath = "../../images/kalem/kalem-siyah.jpg",
                            Name = "Kalem",
                            Price = 150m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Color = "Mavi",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9908),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7415),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Zippo'nun gümüş rengi fırçalanmış görünümlü krom tükenmez kalemi (Ballpoint) pürüzsüz ve şık bir görünüm sunuyor. Çift yönlü açma ve kapama, Zippo logolu sabit metal klips ve orta kalınlıkta siyah uç. Zippo'nun gümüş rengi fırçalanmış krom tükenmez kalemi hediye edilmeye uygun özel doğa dostu karton kutusunda iki yıl garanti kapsamındadır.\r\n•Çift Yönlü Açılma\r\n•Tükenmez Kalem (Ball Point)\r\n•Özel doğa dostu karton kutusunda\r\n•Garanti",
                            ImagePath = "../../images/kalem/kalem-mavi1.jpg",
                            Name = "Kalem",
                            Price = 150m,
                            Quantity = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Color = "Mavi",
<<<<<<<< HEAD:ECommerce.Infrastructure/Migrations/20240412161340_init.Designer.cs
                            CreateDate = new DateTime(2024, 4, 12, 19, 13, 40, 48, DateTimeKind.Local).AddTicks(9909),
========
                            CreateDate = new DateTime(2024, 4, 13, 12, 37, 24, 899, DateTimeKind.Local).AddTicks(7416),
>>>>>>>> origin/Atalay:ECommerce.Infrastructure/Migrations/20240413093725_init.Designer.cs
                            Description = "Zippo'nun gümüş rengi fırçalanmış görünümlü krom ince tükenmez kalemi (Rollerball) pürüzsüz ve şık bir görünüm sunuyor. Aç-kapa kapak özellikli Zippo logolu metal klips ve siyah ucuyla Zippo'nun bu kalemi hediye edilmeye uygun özel doğa dostu karton kutusunda iki yıl garanti kapsamındadır.\r\n•Aç-Kapa Kapak\r\n•İnce Tükenmez Kalem (Roller Ball)\r\n•Özel doğa dostu karton kutusunda\r\n•Garanti",
                            ImagePath = "../../images/kalem/kalem-mavi2.jpg",
                            Name = "Kalem",
                            Price = 150m,
                            Quantity = 5,
                            Status = 1
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.ProductOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Cart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.ProductOrder", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
